/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Pichau
 */
public class ALogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ALogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonNutri = new javax.swing.JLabel();
        buttonPaciente = new javax.swing.JLabel();
        jLabelFotoPaciente = new javax.swing.JLabel();
        jLabelFotoNutri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Login");
        setMinimumSize(new java.awt.Dimension(605, 350));

        jPanel1.setToolTipText("Tela de login");
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 350));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 350));
        jPanel1.setLayout(null);

        ButtonNutri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        ButtonNutri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNutri.setMaximumSize(new java.awt.Dimension(120, 35));
        ButtonNutri.setMinimumSize(new java.awt.Dimension(100, 30));
        ButtonNutri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNutriMouseClicked(evt);
            }
        });
        jPanel1.add(ButtonNutri);
        ButtonNutri.setBounds(370, 260, 200, 70);

        buttonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Paciente.png"))); // NOI18N
        buttonPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPacienteMouseClicked(evt);
            }
        });
        jPanel1.add(buttonPaciente);
        buttonPaciente.setBounds(60, 250, 160, 90);

        jLabelFotoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpeg"))); // NOI18N
        jLabelFotoPaciente.setMinimumSize(new java.awt.Dimension(605, 400));
        jPanel1.add(jLabelFotoPaciente);
        jLabelFotoPaciente.setBounds(-400, -90, 700, 440);

        jLabelFotoNutri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Nutri.jpeg"))); // NOI18N
        jLabelFotoNutri.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFotoNutri.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabelFotoNutri.setMinimumSize(new java.awt.Dimension(605, 400));
        jPanel1.add(jLabelFotoNutri);
        jLabelFotoNutri.setBounds(250, 0, 360, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPacienteMouseClicked
        new BVerificaPaciente().setVisible(true);
        
    }//GEN-LAST:event_buttonPacienteMouseClicked

    private void ButtonNutriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNutriMouseClicked
        new BLoginNutri().setVisible(true);
        
    }//GEN-LAST:event_ButtonNutriMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonNutri;
    private javax.swing.JLabel buttonPaciente;
    private javax.swing.JLabel jLabelFotoNutri;
    private javax.swing.JLabel jLabelFotoPaciente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
